### ISSUE TITLE
跨域资源共享（CORS）详解

### ISSUE THREAD

**Issue by forrestchang** [forrestchang/forrestchang.github.io#1]
http://jiayuanzhang.com/post/cors-tutorial/?code=c35c1605a25a1d179a82

**Comment by forrestchang** [comment]
测试一下 Gittalk 的评论。

**Comment by sunnysabor** [comment]
目前看过关于跨域请求最全面的赞

**Comment by chinaran** [comment]
写的真棒

**Comment by shadowzey** [comment]
关于 **需预检的请求** 的判定条件 当一个请求满足**所有以下**条件时，该请求需要首先发送预检请求。

这句话有问题，应该为 当一个请求满足**以下任一**条件时，该请求需要首先发送预检请求。

参考见 https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

In particular, a request is preflighted if any of the following conditions is true:

**Comment by forrestchang** [comment]
> 关于 **需预检的请求** 的判定条件 当一个请求满足**所有以下**条件时，该请求需要首先发送预检请求。
> 
> 这句话有问题，应该为 当一个请求满足**以下任一**条件时，该请求需要首先发送预检请求。
> 
> 参考见 https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
> 
> In particular, a request is preflighted if any of the following conditions is true:

多谢，已经更正。
